// Copyright ©2021-2025 Mike King.
// This file is licensed to you under the MIT license.
// See the License.txt file in the solution root for more information.

using System.Data.Common;

namespace DotDoc.EntityFrameworkCore.Extensions.ExecuteUpdate;

/// <summary>
/// The query generated by an ExecuteDelete/Insert/Update.
/// </summary>
internal sealed class QueryResult
{
    #region public constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="QueryResult"/> class.
    /// </summary>
    /// <param name="sql">The SQL statement.</param>
    /// <param name="parameters">The parameters.</param>
    public QueryResult(string sql, DbParameter[] parameters)
    {
        this.Sql = sql;
        this.Parameters = parameters;
    }

    #endregion public constructors

    #region public methods

    /// <summary>
    /// Gets the Sql statement.
    /// </summary>
    public string Sql { get; }

    /// <summary>
    /// Gets the parameters.
    /// </summary>
    public DbParameter[] Parameters { get; }

    #endregion public methods
}
